import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";


const geistPoppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: "500"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistPoppins.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
